artifact_location: file:///E:/projects/TrainingFPDModel/End-to-End-DL-Pipeline2/runs/mlflow/0
creation_time: 1767885707307
experiment_id: '0'
last_update_time: 1767885707307
lifecycle_stage: active
name: Default
